server:
  port: 9000

spring:
  application:
    name: springcloud-project-zuul-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-${server.port}
        register: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 15s
        tags: version=1.0£¬author=xugongwei

