server:
  port: 80

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-${server.port}
        register: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 15s
        tags: version=1.0，author=xugongwei
  application:
    name: springcloud-project-comsumer

feign:
  hystrix:
    enabled: true